sonar.projectKey=amurlaniakea_bio-mapping-engine
sonar.organization=amurlaniakea

# Code coverage reports
sonar.python.coverage.reportPaths=coverage.xml

# Source and test directories
sonar.sources=src
sonar.tests=tests

# Encoding
sonar.sourceEncoding=UTF-8
